permalink: /:categories/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Zhengchao Xu
  email: xuzhengchaojob@gmail.com
  link: http://xuzhengchao.com
  github: http://github.com/byrlx
  music: http://book.douban.com/people/134104578

# 站点信息
title: Zhengchao Xu Writings
description: Things a code monkey do at spare time
url: http://xuzhengchao.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-71196319-1
  url: xuzhengchao.com

# disqus 设置
disqus:
  shortname: xuzhengchao

# 主题设置，自动激活某个标签
active: Lisp

# 首页除了最新文章外显示分类
cates: 
  - Android
  - Emacs

# 中文本地化
locals:
  tags: Tags
  about: About
  newest: Newest
  archive: All
